# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - backendapiapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://nodexpress.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b79dfd4712454aa4a9cbe25fa4366eb6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_261ea0508d0f479b894412eaeb395cdb }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: nodexpress.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b79dfd4712454aa4a9cbe25fa4366eb6 }}/travel_api_git:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'backendapiapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a80a92ee3f534a1b92ee4f472e17dae5 }}
        images: 'nodexpress.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b79dfd4712454aa4a9cbe25fa4366eb6 }}/travel_api_git:${{ github.sha }}'